#!/usr/bin/env bash

set -e
[ -n "$DEBUG" ] && set -x

USER=${USER:-$(id -u -n)}
HOME="${HOME:-$(getent passwd $USER 2>/dev/null | cut -d: -f6)}"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

apply() {
    if [ $3 -ne 1 ]; then
        rm -rf "$2"
    fi

    if [[ -e "$1" ]]; then
        ln -s -f "$1" "$2"
    else
        touch "$2"
    fi
}

if which zsh > /dev/null; then
    echo "Configuring Shell (Z Shell)"
    apply "$BASEDIR/zshrc" "$HOME/.zshrc" 0
    apply "$BASEDIR/aliases" "$HOME/.aliases" 0
    apply "$BASEDIR/localrc" "$HOME/.localrc" 1
else
    echo "Z Shell is not installed, skipping setup (including Antigen)"
fi

if which git > /dev/null; then
    echo "Configuring Git"
    apply "$BASEDIR/gitconfig" "$HOME/.gitconfig" 0
    apply "$BASEDIR/gitconfig.local" "$HOME/.gitconfig.local" 1
else
    echo "Git is not installed, skipping setup"
fi

echo -e "\nDone!"
